# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm/llm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm/llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15llm/llm_service.proto\x12\x03llm\"\x83\x01\n\x0b\x43hatRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06\x62ot_id\x18\x03 \x01(\t\x12\x1e\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x0e.llm.LLMConfig\x12\x10\n\x08robot_id\x18\x05 \x01(\t\x12\x10\n\x08trace_id\x18\x06 \x01(\t\"D\n\x0c\x43hatResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x14\n\x0cmetrics_json\x18\x03 \x01(\t\")\n\x13\x43learSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"I\n\x14\x43learSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63leared\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"H\n\tLLMConfig\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x32\x86\x01\n\nLLMService\x12\x33\n\nStreamChat\x12\x10.llm.ChatRequest\x1a\x11.llm.ChatResponse0\x01\x12\x43\n\x0c\x43learSession\x12\x18.llm.ClearSessionRequest\x1a\x19.llm.ClearSessionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm.llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=31
  _globals['_CHATREQUEST']._serialized_end=162
  _globals['_CHATRESPONSE']._serialized_start=164
  _globals['_CHATRESPONSE']._serialized_end=232
  _globals['_CLEARSESSIONREQUEST']._serialized_start=234
  _globals['_CLEARSESSIONREQUEST']._serialized_end=275
  _globals['_CLEARSESSIONRESPONSE']._serialized_start=277
  _globals['_CLEARSESSIONRESPONSE']._serialized_end=350
  _globals['_LLMCONFIG']._serialized_start=352
  _globals['_LLMCONFIG']._serialized_end=424
  _globals['_LLMSERVICE']._serialized_start=427
  _globals['_LLMSERVICE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
