# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llm import llm_service_pb2 as llm_dot_llm__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm/llm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """LLM 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/llm.LLMService/StreamChat',
                request_serializer=llm_dot_llm__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=llm_dot_llm__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ClearSession = channel.unary_unary(
                '/llm.LLMService/ClearSession',
                request_serializer=llm_dot_llm__service__pb2.ClearSessionRequest.SerializeToString,
                response_deserializer=llm_dot_llm__service__pb2.ClearSessionResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """LLM 服务定义
    """

    def StreamChat(self, request, context):
        """流式对话接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearSession(self, request, context):
        """清理服务端会话缓存
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=llm_dot_llm__service__pb2.ChatRequest.FromString,
                    response_serializer=llm_dot_llm__service__pb2.ChatResponse.SerializeToString,
            ),
            'ClearSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearSession,
                    request_deserializer=llm_dot_llm__service__pb2.ClearSessionRequest.FromString,
                    response_serializer=llm_dot_llm__service__pb2.ClearSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """LLM 服务定义
    """

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.LLMService/StreamChat',
            llm_dot_llm__service__pb2.ChatRequest.SerializeToString,
            llm_dot_llm__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/ClearSession',
            llm_dot_llm__service__pb2.ClearSessionRequest.SerializeToString,
            llm_dot_llm__service__pb2.ClearSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
