# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llm import workflow_service_pb2 as llm_dot_workflow__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm/workflow_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub(object):
    """独立复杂任务服务；不得改变现有 LLMService.StreamChat。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyComplex = channel.unary_unary(
                '/workflow.WorkflowService/ClassifyComplex',
                request_serializer=llm_dot_workflow__service__pb2.ClassifyComplexRequest.SerializeToString,
                response_deserializer=llm_dot_workflow__service__pb2.ClassifyComplexResponse.FromString,
                _registered_method=True)
        self.PlanComplex = channel.unary_unary(
                '/workflow.WorkflowService/PlanComplex',
                request_serializer=llm_dot_workflow__service__pb2.PlanComplexRequest.SerializeToString,
                response_deserializer=llm_dot_workflow__service__pb2.PlanComplexResponse.FromString,
                _registered_method=True)
        self.ExecuteStep = channel.unary_unary(
                '/workflow.WorkflowService/ExecuteStep',
                request_serializer=llm_dot_workflow__service__pb2.ExecuteStepRequest.SerializeToString,
                response_deserializer=llm_dot_workflow__service__pb2.ExecuteStepResponse.FromString,
                _registered_method=True)
        self.StreamSynthesis = channel.unary_stream(
                '/workflow.WorkflowService/StreamSynthesis',
                request_serializer=llm_dot_workflow__service__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=llm_dot_workflow__service__pb2.SynthesisChunk.FromString,
                _registered_method=True)
        self.CancelWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/CancelWorkflow',
                request_serializer=llm_dot_workflow__service__pb2.CancelWorkflowRequest.SerializeToString,
                response_deserializer=llm_dot_workflow__service__pb2.CancelWorkflowResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer(object):
    """独立复杂任务服务；不得改变现有 LLMService.StreamChat。
    """

    def ClassifyComplex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanComplex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSynthesis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyComplex': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyComplex,
                    request_deserializer=llm_dot_workflow__service__pb2.ClassifyComplexRequest.FromString,
                    response_serializer=llm_dot_workflow__service__pb2.ClassifyComplexResponse.SerializeToString,
            ),
            'PlanComplex': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanComplex,
                    request_deserializer=llm_dot_workflow__service__pb2.PlanComplexRequest.FromString,
                    response_serializer=llm_dot_workflow__service__pb2.PlanComplexResponse.SerializeToString,
            ),
            'ExecuteStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStep,
                    request_deserializer=llm_dot_workflow__service__pb2.ExecuteStepRequest.FromString,
                    response_serializer=llm_dot_workflow__service__pb2.ExecuteStepResponse.SerializeToString,
            ),
            'StreamSynthesis': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSynthesis,
                    request_deserializer=llm_dot_workflow__service__pb2.SynthesisRequest.FromString,
                    response_serializer=llm_dot_workflow__service__pb2.SynthesisChunk.SerializeToString,
            ),
            'CancelWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelWorkflow,
                    request_deserializer=llm_dot_workflow__service__pb2.CancelWorkflowRequest.FromString,
                    response_serializer=llm_dot_workflow__service__pb2.CancelWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService(object):
    """独立复杂任务服务；不得改变现有 LLMService.StreamChat。
    """

    @staticmethod
    def ClassifyComplex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/ClassifyComplex',
            llm_dot_workflow__service__pb2.ClassifyComplexRequest.SerializeToString,
            llm_dot_workflow__service__pb2.ClassifyComplexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanComplex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/PlanComplex',
            llm_dot_workflow__service__pb2.PlanComplexRequest.SerializeToString,
            llm_dot_workflow__service__pb2.PlanComplexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/ExecuteStep',
            llm_dot_workflow__service__pb2.ExecuteStepRequest.SerializeToString,
            llm_dot_workflow__service__pb2.ExecuteStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSynthesis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/workflow.WorkflowService/StreamSynthesis',
            llm_dot_workflow__service__pb2.SynthesisRequest.SerializeToString,
            llm_dot_workflow__service__pb2.SynthesisChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/CancelWorkflow',
            llm_dot_workflow__service__pb2.CancelWorkflowRequest.SerializeToString,
            llm_dot_workflow__service__pb2.CancelWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
