#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${RUST_CLIENT_ENV_FILE:-$DIR/.env.local}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

export RUST_LOG="${RUN_RUST_LOG:-${RUST_LOG:-info}}"

export GATEWAY_URL="${GATEWAY_URL:-ws://127.0.0.1:8282/ws}"
export ROBOT_ID="${ROBOT_ID:-test_01}"

# ROBOT_SECRET is intentionally not defaulted here. Put it in .env.local or
# export it in the parent shell when the Gateway requires strong auth.

export TRANSPORT_POLICY="${TRANSPORT_POLICY:-webrtc_only}"
export WEBRTC_ENABLED="${WEBRTC_ENABLED:-true}"
export TRANSPORT_FALLBACK_ENABLED="${TRANSPORT_FALLBACK_ENABLED:-false}"
export WEBRTC_OFFER_FACTORY="${WEBRTC_OFFER_FACTORY:-native}"
export RTC_AUDIO_UPLINK="${RTC_AUDIO_UPLINK:-rtp_only}"

export ANGLE_REPORT_URL="${ANGLE_REPORT_URL:-http://127.0.0.1:5200/api/robot/angle}"

export VAD_MODE="${VAD_MODE:-2}"
export VAD_SPEECH_START_MIN_DBFS="${VAD_SPEECH_START_MIN_DBFS:--36}"
export VAD_SILENCE_THRESHOLD="${VAD_SILENCE_THRESHOLD:-0.5}"
export VAD_SPEECH_THRESHOLD="${VAD_SPEECH_THRESHOLD:-0.25}"
export VAD_SPEECH_TRIGGER_RATIO="${VAD_SPEECH_TRIGGER_RATIO:-0.6}"
export VAD_MAX_RECORDING_DURATION="${VAD_MAX_RECORDING_DURATION:-10}"
export TURN_GATE_SHADOW_ENABLED="${TURN_GATE_SHADOW_ENABLED:-false}"
export TURN_GATE_ACTIVE_ENABLED="${TURN_GATE_ACTIVE_ENABLED:-true}"
export TURN_GATE_CANDIDATE_SILENCE_MS="${TURN_GATE_CANDIDATE_SILENCE_MS:-300}"
export TURN_GATE_MIN_COMMIT_SILENCE_MS="${TURN_GATE_MIN_COMMIT_SILENCE_MS:-600}"
export TURN_GATE_FAILURE_FALLBACK_MS="${TURN_GATE_FAILURE_FALLBACK_MS:-1000}"
export TURN_GATE_AMBIGUOUS_HARD_TIMEOUT_MS="${TURN_GATE_AMBIGUOUS_HARD_TIMEOUT_MS:-1600}"

export AUDIO_FRONTEND_MODE="tcp"
export AUDIO_FRONTEND_HOST="${AUDIO_FRONTEND_HOST:-127.0.0.1}"
export AUDIO_FRONTEND_MIC_PORT="${AUDIO_FRONTEND_MIC_PORT:-39001}"
export AUDIO_FRONTEND_SPEAKER_PORT="${AUDIO_FRONTEND_SPEAKER_PORT:-39002}"
export AUDIO_FRONTEND_CONTROL_PORT="${AUDIO_FRONTEND_CONTROL_PORT:-39003}"
export AUDIO_FRONTEND_MUTE_MIC_DURING_PLAYBACK="${AUDIO_FRONTEND_MUTE_MIC_DURING_PLAYBACK:-false}"
export AUDIO_FRONTEND_UPSAMPLER="${AUDIO_FRONTEND_UPSAMPLER:-repeat}"
export TTS_BARGE_IN_WITH_AEC="${TTS_BARGE_IN_WITH_AEC:-false}"
export WAKE_CAPTURE_PREBUFFER_MS="${WAKE_CAPTURE_PREBUFFER_MS:-800}"

export WAKE_SOURCE_MODE="${RUN_AUDIO_FRONTEND_WAKE_SOURCE_MODE:-kws}"
export KWS_WAKE_HOST="${KWS_WAKE_HOST:-127.0.0.1}"
export KWS_WAKE_PORT="${KWS_WAKE_PORT:-${KWS_EVENT_PORT:-39004}}"
export KWS_WAKE_RECONNECT_SEC="${KWS_WAKE_RECONNECT_SEC:-1.0}"

export ASR_DING_SOUND_PATH="${ASR_DING_SOUND_PATH:-$DIR/assets/wake_audio/ding.wav}"

cd "$DIR"
exec cargo run --bin rust_client --features native-webrtc -- "$@"
