# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\x03stt\"Y\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\",\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08\"\xd0\x01\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x0f\n\x07\x65motion\x18\x05 \x01(\t\x12\x12\n\nevent_type\x18\x06 \x01(\t\x12\x10\n\x08raw_text\x18\x07 \x01(\t\x12\x11\n\ttags_json\x18\x08 \x01(\t\x12\x15\n\rmetadata_json\x18\t \x01(\t\x12\x19\n\x11\x63onfidence_source\x18\n \x01(\t2\x80\x01\n\nSTTService\x12\x37\n\x0fRecognizeSpeech\x12\x11.stt.AudioRequest\x1a\x11.stt.TextResponse\x12\x39\n\x0fStreamRecognize\x12\x0f.stt.AudioChunk\x1a\x11.stt.TextResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=26
  _globals['_AUDIOREQUEST']._serialized_end=115
  _globals['_AUDIOCHUNK']._serialized_start=117
  _globals['_AUDIOCHUNK']._serialized_end=161
  _globals['_TEXTRESPONSE']._serialized_start=164
  _globals['_TEXTRESPONSE']._serialized_end=372
  _globals['_STTSERVICE']._serialized_start=375
  _globals['_STTSERVICE']._serialized_end=503
# @@protoc_insertion_point(module_scope)
