services:
  wzk-stt:
    # image: vllm/vllm-openai:v0.21.0
    image: wzk/vllm-qwen3-asr:v0.21.0-audio
    container_name: wzk-stt
    restart: unless-stopped
    ipc: host

    ports:
      - "${ASR_VLLM_PORT}:8000"

    volumes:
      - /home/chase/datasets/wzk/models:/models
      - /home/chase/datasets/wzk/hf-cache:/root/.cache/huggingface

    environment:
      NVIDIA_VISIBLE_DEVICES: "${ASR_CUDA_VISIBLE_DEVICES}"
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      HF_HOME: /root/.cache/huggingface

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${ASR_CUDA_VISIBLE_DEVICES}"]
              capabilities: ["gpu"]

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

    entrypoint: ["vllm", "serve"]

    command:
      - ${ASR_MODEL_PATH}
      - --served-model-name
      - ${ASR_SERVED_MODEL_NAME}
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --dtype
      - auto
      - --gpu-memory-utilization
      - ${ASR_GPU_MEMORY_UTILIZATION}
      - --max-model-len
      - ${ASR_MAX_MODEL_LEN}
      - --trust-remote-code
      - --api-key
      - ${ASR_VLLM_API_KEY}

    networks:
      - wzk-ai-net

networks:
  wzk-ai-net:
    external: true
