# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tts_service.proto\x12\x03tts\"#\n\tTTSConfig\x12\x16\n\x0etts_profile_id\x18\x01 \x01(\t\"\xb7\x01\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x1e\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x0e.tts.TTSConfig\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\x10\n\x08round_id\x18\x06 \x01(\t\x12\x13\n\x0bplayback_id\x18\x07 \x01(\t\x12\x1d\n\x15gateway_send_epoch_ms\x18\x08 \x01(\x01\"\xce\x03\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x14\n\x0csample_width\x18\x04 \x01(\x05\x12\x10\n\x08is_final\x18\x05 \x01(\x08\x12\x10\n\x08trace_id\x18\x06 \x01(\t\x12\x10\n\x08round_id\x18\x07 \x01(\t\x12\x13\n\x0bplayback_id\x18\x08 \x01(\t\x12#\n\x1btts_server_receive_epoch_ms\x18\t \x01(\x01\x12\'\n\x1ftts_first_text_receive_epoch_ms\x18\n \x01(\x01\x12$\n\x1ctts_first_text_send_epoch_ms\x18\x0b \x01(\x01\x12\x1e\n\x16tts_first_pcm_epoch_ms\x18\x0c \x01(\x01\x12\x1f\n\x17tts_grpc_yield_epoch_ms\x18\r \x01(\x01\x12!\n\x19tts_internal_first_pcm_ms\x18\x0e \x01(\x01\x12&\n\x1etts_first_text_to_first_pcm_ms\x18\x0f \x01(\x01\x12$\n\x1ctts_request_to_grpc_yield_ms\x18\x10 \x01(\x01\x32G\n\nTTSService\x12\x39\n\x12StreamTextToSpeech\x12\x0e.tts.TextChunk\x1a\x0f.tts.AudioChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSCONFIG']._serialized_start=26
  _globals['_TTSCONFIG']._serialized_end=61
  _globals['_TEXTCHUNK']._serialized_start=64
  _globals['_TEXTCHUNK']._serialized_end=247
  _globals['_AUDIOCHUNK']._serialized_start=250
  _globals['_AUDIOCHUNK']._serialized_end=712
  _globals['_TTSSERVICE']._serialized_start=714
  _globals['_TTSSERVICE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
